apiVersion: apps/v1
kind: Deployment
metadata:
  name: arrienda-back
  namespace: back
spec:
  selector:
    matchLabels:
      app: arrienda-back
  replicas: 1
  template:
    metadata:
      labels:
         app: arrienda-back
    spec:
      imagePullSecrets:
         - name: github-secret
      containers:
         - name: arrienda
           image: localhost:5000/imagen_back
           ports:
              - containerPort: 8082
           
---
apiVersion: v1
kind: Service
metadata:
  name: arrienda-back
  namespace: back
spec:
  selector:
    app: arrienda-back
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8082
